# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harsh Patel 
email: harsh.patel54@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Innovation, Disruption, Blockchains, Technology & Economics. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://18dew.github.io" # the base hostname & protocol for your site
twitter_username: 18dew
github_username:  18dew

# Build settings
markdown: kramdown
